//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ipanema {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Ipanema : global::System.Configuration.ApplicationSettingsBase {
        
        private static Ipanema defaultInstance = ((Ipanema)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Ipanema())));
        
        public static Ipanema Default {
            get {
                return defaultInstance;
            }
        }
    }
}
